// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SeleniumTests.Features.HomePage
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("PerfectMatch", SourceFile="Features\\HomePage\\PerfectMatch.feature", SourceLine=0)]
    public partial class PerfectMatchFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PerfectMatch.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "PerfectMatch", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void PerfectMatchRedirectsToCorrectOutfitBuilderTab(string colour, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Perfect Match redirects to correct outfit builder tab", exampleTags);
#line 3
this.ScenarioSetup(scenarioInfo);
#line 4
 testRunner.Given("I am on the Xedo Home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 5
 testRunner.When(string.Format("I select the perfect match colour {0}", colour), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 6
 testRunner.Then("I am on the Xedo OutfitBuilder page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 7
 testRunner.And("the neckwear filter is expanded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.And(string.Format("the colour {0} filter is selected", colour), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Perfect Match redirects to correct outfit builder tab, black", SourceLine=11)]
        public virtual void PerfectMatchRedirectsToCorrectOutfitBuilderTab_Black()
        {
            this.PerfectMatchRedirectsToCorrectOutfitBuilderTab("black", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Perfect Match redirects to correct outfit builder tab, teal", SourceLine=11)]
        public virtual void PerfectMatchRedirectsToCorrectOutfitBuilderTab_Teal()
        {
            this.PerfectMatchRedirectsToCorrectOutfitBuilderTab("teal", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Perfect Match redirects to correct outfit builder tab, blue", SourceLine=11)]
        public virtual void PerfectMatchRedirectsToCorrectOutfitBuilderTab_Blue()
        {
            this.PerfectMatchRedirectsToCorrectOutfitBuilderTab("blue", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Perfect Match redirects to correct outfit builder tab, green", SourceLine=11)]
        public virtual void PerfectMatchRedirectsToCorrectOutfitBuilderTab_Green()
        {
            this.PerfectMatchRedirectsToCorrectOutfitBuilderTab("green", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Perfect Match redirects to correct outfit builder tab, purple", SourceLine=11)]
        public virtual void PerfectMatchRedirectsToCorrectOutfitBuilderTab_Purple()
        {
            this.PerfectMatchRedirectsToCorrectOutfitBuilderTab("purple", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Perfect Match redirects to correct outfit builder tab, grey", SourceLine=11)]
        public virtual void PerfectMatchRedirectsToCorrectOutfitBuilderTab_Grey()
        {
            this.PerfectMatchRedirectsToCorrectOutfitBuilderTab("grey", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Perfect Match redirects to correct outfit builder tab, red", SourceLine=11)]
        public virtual void PerfectMatchRedirectsToCorrectOutfitBuilderTab_Red()
        {
            this.PerfectMatchRedirectsToCorrectOutfitBuilderTab("red", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Perfect Match redirects to correct outfit builder tab, tan", SourceLine=11)]
        public virtual void PerfectMatchRedirectsToCorrectOutfitBuilderTab_Tan()
        {
            this.PerfectMatchRedirectsToCorrectOutfitBuilderTab("tan", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Perfect Match redirects to correct outfit builder tab, pink", SourceLine=11)]
        public virtual void PerfectMatchRedirectsToCorrectOutfitBuilderTab_Pink()
        {
            this.PerfectMatchRedirectsToCorrectOutfitBuilderTab("pink", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Perfect Match redirects to correct outfit builder tab, yellow", SourceLine=11)]
        public virtual void PerfectMatchRedirectsToCorrectOutfitBuilderTab_Yellow()
        {
            this.PerfectMatchRedirectsToCorrectOutfitBuilderTab("yellow", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Perfect Match redirects to correct outfit builder tab, ivory", SourceLine=11)]
        public virtual void PerfectMatchRedirectsToCorrectOutfitBuilderTab_Ivory()
        {
            this.PerfectMatchRedirectsToCorrectOutfitBuilderTab("ivory", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("PerfectMatch")]
    public partial class PerfectMatchFeature_NUnit
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PerfectMatch.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "PerfectMatch", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Perfect Match redirects to correct outfit builder tab")]
        [NUnit.Framework.TestCaseAttribute("black", new string[0])]
        [NUnit.Framework.TestCaseAttribute("teal", new string[0])]
        [NUnit.Framework.TestCaseAttribute("blue", new string[0])]
        [NUnit.Framework.TestCaseAttribute("green", new string[0])]
        [NUnit.Framework.TestCaseAttribute("purple", new string[0])]
        [NUnit.Framework.TestCaseAttribute("grey", new string[0])]
        [NUnit.Framework.TestCaseAttribute("red", new string[0])]
        [NUnit.Framework.TestCaseAttribute("tan", new string[0])]
        [NUnit.Framework.TestCaseAttribute("pink", new string[0])]
        [NUnit.Framework.TestCaseAttribute("yellow", new string[0])]
        [NUnit.Framework.TestCaseAttribute("ivory", new string[0])]
        public virtual void PerfectMatchRedirectsToCorrectOutfitBuilderTab(string colour, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Perfect Match redirects to correct outfit builder tab", exampleTags);
#line 3
this.ScenarioSetup(scenarioInfo);
#line 4
 testRunner.Given("I am on the Xedo Home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 5
 testRunner.When(string.Format("I select the perfect match colour {0}", colour), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 6
 testRunner.Then("I am on the Xedo OutfitBuilder page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 7
 testRunner.And("the neckwear filter is expanded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.And(string.Format("the colour {0} filter is selected", colour), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
